// <auto-generated />
using System;
using Convy.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Convy.Data.Migrations
{
    [DbContext(typeof(ConvyDbContext))]
    [Migration("20261007162823_AddSearchCache")]
    partial class AddSearchCache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Convy.Data.Entities.DownloadStateEntry", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemRef")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Provider", "ItemRef");

                    b.ToTable("DownloadStates");
                });

            modelBuilder.Entity("Convy.Data.Entities.FileEntry", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoHash")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LinkedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("TorrentName")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Provider", "InfoHash", "FilePath");

                    b.ToTable("FileEntries");
                });

            modelBuilder.Entity("Convy.Data.Entities.FileListingEntry", b =>
                {
                    b.Property<string>("ResultId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TorrentFile")
                        .HasColumnType("BLOB");

                    b.HasKey("ResultId");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("FileListings");
                });

            modelBuilder.Entity("Convy.Data.Entities.JobEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientCategory")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemRef")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("LastDownloadedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastProgressAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlacementAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rule")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedFilesJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subpath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Provider", "ItemRef");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Convy.Data.Entities.SearchResultEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvailabilityJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DedupKey")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchedQueriesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SearchId", "DedupKey");

                    b.ToTable("SearchResults");
                });

            modelBuilder.Entity("Convy.Data.Entities.SearchSessionEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextSourceIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueriesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("SearchSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
