// <auto-generated />
using System;
using Convy.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Convy.Data.Migrations
{
    [DbContext(typeof(ConvyDbContext))]
    [Migration("20261007160112_ReplaceTorrentStatesWithDownloadStates")]
    partial class ReplaceTorrentStatesWithDownloadStates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Convy.Data.Entities.DownloadStateEntry", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemRef")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Provider", "ItemRef");

                    b.ToTable("DownloadStates");
                });

            modelBuilder.Entity("Convy.Data.Entities.FileEntry", b =>
                {
                    b.Property<string>("InfoHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LinkedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("TorrentName")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("InfoHash", "FilePath");

                    b.ToTable("FileEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
